config/routes.rb
Rails.application.routes.draw do
#  get 'sessions/index'

  get 'projects/index'

  get 'projects/new'

  get 'projects/edit'

  get 'projects/_form'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/dashboard'
  get 'dashboard' => 'dashboard#index', as: :dashboard_url
  devise_for :users, controllers: {
		sessions: 'users/sessions',
		passwords: 'users/passwords',
		registrations: 'users/registrations'
	  }
  get 'home/index'
  resources :projects
  #resources :sessions, only: [:update]
  root to: "home#index"
  # Para más detalles sobre el DSL disponibles dentro de este archivo, consulte,
  # see http://guides.rubyonrails.org/routing.html

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   skip_before_action :authenticate_user!, :only => [:index]
  def index
  	
	#skip_before_action :authenticate_user!, :only => [:index]
	#skip_before_action :redirect_heroku_user, only: :edit, raise: false
  end

  def dashboard
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/dashboard.html.erb
<div class="page-header">

	<h1>Welcomeee!</h1>
    <h2>TU Role es:</h2>
            
            <% if current_user.superadmin_role? %>
               ADMIN         
            <% end %>
             <% if current_user.supervisor_role? %>
               SUPER VISOR         
            <% end %>
            <% if current_user.user_role? %>
                UN MORTAL
            <% end %>
</div>

<% if can? :manage, User %>
	<p>Visible only for superadmins and supervisors! </p>
	<%= link_to "Panel Administrativo", "../admin", :target => "_blank",class: 'btn btn-lg btn-primary'  %>
<% else %>

    <p>Simple Mortal! </p>
<% end %>

<% if can? :index, Project %>
  <%= link_to 'Projects', projects_path, class: 'btn btn-lg btn-primary' %>
<% end %>

<ul class="nav navbar-nav">
  <% if can? :create, Project %>
    <li><%= link_to 'Add Project', new_project_path %></li>
  <% end %>
</ul>

<a class="dropdown-toggle" aria-expanded="false" role="button" data-toggle="dropdown" href="#">
      

app/views/home/index.html.erb
<% if can? :manage, User %>
	<p>Visible only for superadmins and supervisors! </p>
	<%= link_to "Panel Administrativo", "../admin", :target => "_blank",class: 'btn btn-lg btn-primary'  %>
<% else %>

    <p>Simple Mortal! </p>
<% end %>

<% if can? :index, Project %>
  <%= link_to 'Projects', projects_path, class: 'btn btn-lg btn-primary' %>
<% end %>

<ul class="nav navbar-nav">
  <% if can? :create, Project %>
    <li><%= link_to 'Add Project', new_project_path %></li>
  <% end %>
</ul>