config/routes.rb
Rails.application.routes.draw do
#  get 'sessions/index'

  get 'projects/index'

  get 'projects/new'

  get 'projects/edit'

  get 'projects/_form'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'home/dashboard'
  get 'dashboard' => 'dashboard#index', as: :dashboard_url
  devise_for :users, controllers: {
		sessions: 'users/sessions',
		passwords: 'users/passwords',
		registrations: 'users/registrations'
	  }
  get 'home/index'
  resources :projects
  #resources :sessions, only: [:update]
  root to: "home#index"
  # Para más detalles sobre el DSL disponibles dentro de este archivo, consulte,
  # see http://guides.rubyonrails.org/routing.html

end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   before_action :load_projects, only: :index
  load_and_authorize_resource

  def index
    #authorize! :index, @projects
  end

  def new
    #@project = Project.new
    #authorize! :new, @project
  end

  def edit

  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = 'Project was updated!'
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def create
    if @project.save
      flash[:success] = 'Project was saved!'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    if @project.destroy
      flash[:success] = 'Project was destroyed!'
    else
      flash[:warning] = 'Cannot destroy this project...'
    end
    redirect_to root_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :ongoing)
  end

  def load_projects
    @projects = Project.accessible_by(current_ability).order('created_at DESC')
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :ongoing %>
    <%= f.check_box :ongoing %>
  </div>

  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header"><h1>Edit Project</h1></div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header"><h1>Projects</h1></div>

<% @projects.each do |project| %>
  <div class="well well-sm">
    <h2><%= project.title %></h2>
    <% if can? :update, project %>
      <%= link_to 'Edit', edit_project_path(project), class: 'btn btn-info' %>
    <% end %>

    <% if can? :destroy, project %>
      <%= link_to 'Delete', project_path(project), class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </div>
<% end %>

app/views/projects/new.html.erb
<div class="page-header"><h1>New Project</h1></div>

<%= render 'form' %>